config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true
  validates :post_id, presence: true
  validates :user_id, presence: true

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :user_id, presence: true

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  #before save
  before_save {email.downcase!}

  #validitations
  validates :name, presence: true, length: {minimum: 3, maximum: 16}

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: {with: EMAIL_REGEX},
                    uniqueness: { case_sensitive: false }

  #associations
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  def show
    @post = Post.find(params[:id])
  end
  def new
    @post = Post.new
  end
  def create
    @post = Post.new
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]


    @post.valid?
    puts @post.errors.messages
    
    if @post.valid?
      @post.save
      redirect_to @post
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<li>
<strong><%= comment.user.name%></strong><br>
<%= comment.body %><br><br>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MicroReddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<li><%= link_to "#{post.title}", post%><br>
    <%= post.body%>
</li>

app/views/posts/index.html.erb
<ul>
  <%= render @posts%>
</ul>

<%= link_to "New Post", new_post_path %>

app/views/posts/new.html.erb
<%= form_for @post do |f|%>
  <%= f.label :title%>
  <%= f.text_area :title%><br>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<%= @post.title %><br>
<%= @post.body %><br><br>

<ul>
  <%= render @post.comments %>
</ul>